name: CI Pipeline

on:
  push:
    branches: [ main, develop, fix-calculator-tests ]
  pull_request:
    branches: [ main ]

jobs:
  # NEW: separate lint job (runs in parallel with tests)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 app/ tests/ --max-line-length=120

  test:
    runs-on: ubuntu-latest
    # NOTE: no "needs" here, so test and lint run in parallel
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run all tests
        run: |
          pytest tests/test_calculator_pass.py tests/test_calculator_fail.py -v

  build:
    # build should only run after BOTH lint and test succeed (we’ll wire this later)
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build application
        run: |
          echo "Building application..."
          echo "Build successful!"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          echo "Deployment successful!"

